apiVersion: v1
kind: Service
metadata:
  name: sot-api
  labels:
    app: sot-api
    role: backend
    service: api
spec:
  selector:
    app: sot-api
    role: backend
  type: LoadBalancer
  #sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: admin
      port: 9990
      targetPort: 9990
      protocol: TCP