apiVersion: v1
kind: Service
metadata:
  name: sot-api
  labels:
    app: sot-api
    role: backend
    service: api
spec:
  selector:
    app: sot-api
    role: backend
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: admin
      port: 9092
      targetPort: admin
      protocol: TCP