apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sot-api
  labels:
    app: sot-api
    role: backend
    service: api
spec:
  replicas: 1
  template:
    metadata:
      name: sot-api
      labels:
        app: sot-api
        role: backend
        env: dev
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port=8080",
#            "--ssl_port", "443",
            "--backend=127.0.0.1:8082",
            "--service=${END_POINT_SERVICE}",
            "--version=${END_POINT_SERVICE_VERSION}",
          ]
          ports:
            - name: http
              containerPort: 8080
            #- containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/creds
              name: service-account-creds
              readOnly: true
            #- mountPath: /etc/nginx/ssl
             # name: nginx-ssl
              #readOnly: true
        - name: sot-api
          image: ${API_IMAGE}
          ports:
            - name: http
              containerPort: 8082
            - name: admin
              containerPort: 9092
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "12Gi"
              cpu: "4"
          imagePullPolicy: IfNotPresent
          env:
            - name: LICENCE_PORT
              value: "80"
            - name: AWS_SECRET_ACCESS_KEY
              value: w2lFZ4umi6Bw3BHjtfhh68caj1rkxx0CggLXsMMK
            - name: AWS_ACCESS_KEY_ID
              value: AKIAIVPAR6IBVVNHRQGQ
            - name: EXECUTOR_DAO_PREFIX
              value: ${EXECUTOR_DAO_PREFIX}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /api/2/health
              port: 8082
      volumes:
        - name: service-account-creds
          secret:
            secretName: service-account-creds
        #- name: nginx-ssl
         # secret:
          #  secretName: nginx-ssl
      #dnsPolicy: ClusterFirst
      #restartPolicy: Always
      #securityContext: {}
      #terminationGracePeriodSeconds: 30